schema_version = "1.0.0"

id = "auto_reload"
version = "3.1.1"
name = "Auto Reload"
tagline = "Automatic reload for external files"
maintainer = "tonton <samytichadou@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/samytichadou/Auto_Reload_Blender_addon"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Import-Export", "Pipeline"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Checking/Reloading external files from current blend"
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"
